service: payment-api-lambda

provider:
  name: aws
  region: eu-central-1
  stage: ${opt:stage, 'test'}

package:
  artifact: target/scala-2.13/payment-api-lambda.jar

functions:
  payment:
    handler: com.hasael.paymentapi.LambdaEntryPoint::handle
    runtime: java11
    memorySize: 2048
    timeout: 30
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors:
            - enabled: true