service: payment-api-lambda

provider:
  name: aws
  runtime: java8
  memorySize: 512
  region: eu-central-1
  stage: ${opt:stage, 'test'}

package:
  artifact: target/scala-2.12/payment-api-lambda.jar

functions:
  hello:
    handler: LambdaEntryPoint::handle
    # Add the following lines:
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors:
            - enabled: true